import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/web/Footer";

// Import Source Sans 3 from Google Fonts (Next.js 13+)
import { Source_Sans_3 } from "next/font/google";

// Initialize the font
const sourceSansPro = Source_Sans_3({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Regular, SemiBold, Bold
});

export const metadata: Metadata = {
  title: "Coming Soon - Wasabi Gaming",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sourceSansPro.className} antialiased`}
        style={{
          background: "linear-gradient(174.98deg, #FDF063 -4.84%, #FEFBDD 105.75%)",
        }}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
